### ISSUE TITLE
[Bug] Binding errors

### ISSUE THREAD

**Issue by reloadif** [IDerkBot/Arion.Style#1]
### Описание проблем

1. Styles -> ArionUI-> PasswordBox -> ScrollViewer имеет неверную привязку Width="{Binding RelativeSource={RelativeSource TemplatedParent}}".
2. Styles -> ArionUI-> TabItem -> LinearGradientBrush.StartEndpoint, LinearGradientBrush.EndPoint, Gradient.StopColor, проблема в RelativeSource={RelativeSource AncestorType=TabItem}.
3. Controls-> RangeSlider -> Name="Thumb2" неверная привязка Margin="{Binding ElementName=Root, Path=RightThumbMargin}", Brd2 неверная привязка Margin="{Binding ElementName=Root, Path=RightThumbMargin}", 47 строка Border неверная привязка Margin="{Binding ElementName=Root, Path=CenterMargin}", Name="CenterThumb" неверная привязка Margin="{Binding ElementName=Root, Path=CenterMargin}". Везде целевой объект Margin, а конечный тип Thickness.

**Comment by chornyi-xrs** [comment]
Решено в рамках [fix: bindings](https://github.com/Arion-Soft/Arion.Style/commit/65b4bf5a5b3faefc19291ffa00e6ab37ee69c28d)
